sudo: required 
services:   
  - docker
before_install:
  - docker build -t pshastri -f Dockerfile.dev .
script:
  - docker run -e CI=true pshastri npm run test
deploy:
  provider: elasticbeanstalk 
  region: "us-east-2" 
  app: "docker" 
  env: "Docker-env" 
  bucket_name: "elasticbeanstalk-us-east-2-719388923443" 
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_access 
  secret_access_key:
    secure: "$AWS_Secret_Key"